---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.7
  - name: ubuntu-14.04
suites:
  - name: auth-server
    run_list:
      - recipe[mozilla-firefox-accounts::fxa-auth-server]
    attributes:
      mysql:
        server_root_password: test
      mozilla-firefox-accounts:
        database:
          password: test

  - name: content-server
    run_list:
      - recipe[mozilla-firefox-accounts::fxa-content-server]
    attributes:
      mysql:
        server_root_password: test
      mozilla-firefox-accounts:
        database:
          password: test

  - name: default
    run_list:
      - recipe[mozilla-firefox-accounts::fxa-auth-server]
      - recipe[mozilla-firefox-accounts::fxa-content-server]
    attributes:
      mysql:
        server_root_password: test
      mozilla-firefox-accounts:
        database:
          password: test

